services:
  bind9:
    image: ubuntu/bind9:9.16-20.04_beta
    container_name: dns-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    
    volumes:
      - ./config/named.conf.options:/etc/bind/named.conf.options
      - ./config/named.conf.local:/etc/bind/named.conf.local
      - ./config/zones:/var/lib/bind
    
    restart: unless-stopped